[config]
schemaVersion = "0.0.1"

[package]
namespace = "MrGlim"
name = "ShipTeleportTerminal"
versionNumber = "1.0.2"
description = "Terminal TELEPORT/TP (and ITELEPORT/ITP) to fire the ship teleporter. Host recommended."
websiteUrl = "https://github.com/ben-hough/lc-ship-teleport-terminal"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
iconPath = "icon.png"
readmePath = "README.md"
outdir = "../build-ShipTeleportTerminal"

[[build.copy]]
source = "ShipTeleportTerminal.dll"
target = "ShipTeleportTerminal.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["mods", "serverside", "tweaks-and-quality-of-life", "ai-generated"]
